avatar_width: 200
avatar_height: 200
avatar_accept_file: "image/jpeg,image/gif,image/png"
remembered: "1"
per_page: 5
number_words: 3
max_answer: 5
answer_default: 2
activity_user_create: 0
activity_user_update: 1
activity_follow: 2
activity_unfollow: 3
activity_lesson_create: 4
activity_lesson_do: 5
activity_user_login: 6
activity_user_logout: 7
avatar_default: "account.jpg"
filter_learned: "learned"
filter_not_learned: "not_learned"
filter_all: "all_words"
filter_options:
  - "learned"
  - "not_learned"
  - "all_words"
